name: keyboard_attachable
description: A Flutter package to build widgets that can be attached to the soft keyboard.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  keyboard_visibility: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: